# This file is managed centrally by modulesync
#   https://github.com/theforeman/foreman-installer-modulesync

source 'https://rubygems.org'

gem 'puppet', ENV.key?('PUPPET_VERSION') ? "~> #{ENV['PUPPET_VERSION']}" : '>= 2.7'

if RUBY_VERSION.start_with? '1.8'
  gem 'rake', '< 11'
  gem 'rspec', '>= 3', '< 3.2'
  gem 'rspec-puppet-facts', '< 1.4.0'
else
  gem 'rake'
  gem 'rspec', '~> 3.0'
  gem 'rspec-puppet-facts', '>= 1.5'
end
<% (@configs['required'] + (@configs['extra'] || [])).each do |gem| -%>
gem '<%= gem['gem'] %>'<%= ", '#{gem['version']}'" if gem['version'] %><%= ", #{gem['options'].inspect}" if gem['options'] %>
<% end -%>

# vim:ft=ruby
